version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
